development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: stimulus_reflex_expo_development

test:
  adapter: test

production:
  adapter: async
  channel_prefix: stimulus_reflex_expo_production
